"""
Renders nat_rules.json -> modules/panos-baseline/nat_policy.tf
Uses panos_nat_rule_group (non-deprecated) for agent-managed NAT rules.
The original nat_untrust_trust rule stays in main.tf as panos_nat_policy.
"""
import json
from pathlib import Path
from jinja2 import Template

TEMPLATE = """# Generated by render_nat_policy.py — do not edit by hand.
{% if rules %}
resource "panos_nat_rule_group" "agent_nat_rules" {
  vsys = "vsys1"

{% for rule in rules %}
  rule {
    name     = {{ rule.name | tojson }}
    disabled = {{ rule.disabled }}

    original_packet {
      source_zones          = {{ rule.source_zones }}
      destination_zone      = {{ rule.destination_zone | tojson }}
      source_addresses      = {{ rule.source_addresses }}
      destination_addresses = {{ rule.destination_addresses }}
      service               = {{ rule.service | tojson }}
    }

    translated_packet {
{% if rule.sat_type == "dynamic-ip-and-port" %}
      source {
        dynamic_ip_and_port {}
      }
{% elif rule.sat_type == "dynamic-ip" %}
      source {
        dynamic_ip {
          translated_addresses = {{ rule.sat_translated_addresses }}
        }
      }
{% elif rule.sat_type == "static-ip" %}
      source {
        static_ip {
          translated_address = {{ rule.sat_static_translated_address | tojson }}
          bi_directional     = {{ rule.sat_static_bi_directional }}
        }
      }
{% endif %}
{% if rule.dat_address %}
      destination {
        static_translation {
          address = {{ rule.dat_address | tojson }}
{% if rule.dat_port %}
          port    = {{ rule.dat_port }}
{% endif %}
        }
      }
{% else %}
      destination {}
{% endif %}
    }
  }
{% endfor %}
}
{% else %}
# No agent-managed NAT rules yet.
{% endif %}
"""

def hcl_list(values):
    return "[" + ", ".join(json.dumps(v) for v in values) + "]"


def render_nat_rules_to_string(rules):
    prepared = []
    for r in rules:
        prepared.append({
            "name": r["name"],
            "disabled": "true" if r.get("disabled") else "false",
            "source_zones": hcl_list(r["source_zones"]),
            "destination_zone": r["destination_zone"],
            "source_addresses": hcl_list(r["source_addresses"]),
            "destination_addresses": hcl_list(r["destination_addresses"]),
            "service": r.get("service", "any"),
            "sat_type": r.get("sat_type", "dynamic-ip-and-port"),
            "sat_translated_addresses": hcl_list(r.get("sat_translated_addresses") or []),
            "sat_static_translated_address": r.get("sat_static_translated_address", ""),
            "sat_static_bi_directional": "true" if r.get("sat_static_bi_directional") else "false",
            "dat_address": r.get("dat_address", ""),
            "dat_port": r.get("dat_port", ""),
        })
    return Template(TEMPLATE).render(rules=prepared)


def render(rules_path="nat_rules.json",
           output_path="modules/panos-baseline/nat_policy.tf"):
    rules = json.loads(Path(rules_path).read_text())
    Path(output_path).write_text(render_nat_rules_to_string(rules))
    print(f"Rendered {len(rules)} agent NAT rule(s) to {output_path}")


if __name__ == "__main__":
    render()
