import json
from jinja2 import Template

TEMPLATE = """# Generated by render_policy.py from rules.json — do not edit by hand.
resource "panos_security_policy" "policies" {
{% for rule in rules %}
  rule {
    name                  = "{{ rule.name }}"
    source_zones          = {{ rule.source_zones }}
    source_addresses      = {{ rule.source_addresses }}
    source_users          = {{ rule.source_users }}
    destination_zones     = {{ rule.destination_zones }}
    destination_addresses = {{ rule.destination_addresses }}
    applications          = {{ rule.applications }}
    services              = {{ rule.services }}
    categories            = {{ rule.categories }}
    action                = "{{ rule.action }}"
    log_end               = {{ rule.log_end }}
  }
{% endfor %}
}
"""

def hcl_list(values):
    return "[" + ", ".join(json.dumps(v) for v in values) + "]"

def render_rules_to_string(rules):
    prepared = [{
        "name": r["name"],
        "source_zones": hcl_list(r["source_zones"]),
        "source_addresses": hcl_list(r["source_addresses"]),
        "source_users": hcl_list(r["source_users"]),
        "destination_zones": hcl_list(r["destination_zones"]),
        "destination_addresses": hcl_list(r["destination_addresses"]),
        "applications": hcl_list(r["applications"]),
        "services": hcl_list(r["services"]),
        "categories": hcl_list(r["categories"]),
        "action": r["action"],
        "log_end": "true" if r["log_end"] else "false",
    } for r in rules]
    return Template(TEMPLATE).render(rules=prepared)

def render(rules_path, output_path):
    with open(rules_path) as f:
        rules = json.load(f)
    rendered = render_rules_to_string(rules)
    with open(output_path, "w") as f:
        f.write(rendered)
    print(f"Wrote {len(rules)} rule(s) to {output_path}")

if __name__ == "__main__":
    render("rules.json", "modules/panos-baseline/policies.tf")
