# Generated by render_policy.py from rules.json — do not edit by hand.
resource "panos_security_policy" "policies" {

  rule {
    name                  = "allow-inbound-http"
    source_zones          = ["untrust"]
    source_addresses      = ["any"]
    source_users          = ["any"]
    destination_zones     = ["trust"]
    destination_addresses = ["web-server"]
    applications          = ["web-browsing"]
    services              = ["application-default"]
    categories            = ["any"]
    action                = "allow"
    log_end               = true
  }

  rule {
    name                  = "allow_ping"
    source_zones          = ["trust"]
    source_addresses      = ["any"]
    source_users          = ["any"]
    destination_zones     = ["trust"]
    destination_addresses = ["any"]
    applications          = ["icmp", "ping"]
    services              = ["application-default"]
    categories            = ["any"]
    action                = "allow"
    log_end               = true
  }

  rule {
    name                  = "ping_vm"
    source_zones          = ["untrust"]
    source_addresses      = ["192.168.43.101/32"]
    source_users          = ["any"]
    destination_zones     = ["trust"]
    destination_addresses = ["192.168.63.64/32"]
    applications          = ["any"]
    services              = ["application-default"]
    categories            = ["any"]
    action                = "allow"
    log_end               = true
  }

  rule {
    name                  = "allow-ssh-10.10.10.10-to-10.50.50.50"
    source_zones          = ["untrust"]
    source_addresses      = ["10.10.10.10"]
    source_users          = ["any"]
    destination_zones     = ["trust"]
    destination_addresses = ["10.50.50.50"]
    applications          = ["ssh"]
    services              = ["application-default"]
    categories            = ["any"]
    action                = "allow"
    log_end               = true
  }

}